//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanSach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportDetail
    {
        public int ImportID { get; set; }
        public int ProductID { get; set; }
        public Nullable<double> Price_Import { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<double> Money { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual Import Import { get; set; }
        public virtual Product Product { get; set; }
    }
}
