//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanSach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public string OrderID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Pay_ID { get; set; }
        public string Name_Deceived { get; set; }
        public string Address_Deceived { get; set; }
        public Nullable<int> Phone_Deceived { get; set; }
        public string Address_Pay { get; set; }
        public Nullable<int> Phone_Pay { get; set; }
        public Nullable<double> SumMoney { get; set; }
        public string State { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Payment Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
